### ISSUE TITLE
[BUG] 'destroy' doesn't cleanup properly

### ISSUE THREAD

**Issue by dpkshetty** [ocp-power-automation/openshift-install-power#118] opened 2021-01-04 15:38 UTC
**Describe the bug**
`openshift-install-powervs destroy` doesn't cleanup properly for someone to start afresh second time

**To Reproduce**
1. `openshift-install-powervs destroy`
2. Wait for cluster to get destroyed
3. delete old COS images & Upload new / updated COS images
4. `openshift-install-powervs create` fails with errors that references old image IDs

**Expected behavior**
'destroy' should cleanup the install dir such that a fresh 'create' works flawlessly

**Console Output**
forgot to capture the screenshot

**Desktop (please complete the following information):**
 - OS: [e.g. RHEL, Ubuntu]
 - Version [e.g. 8.3, 16.04]
 - Windows terminal [eg: Cygwin, GitBash]

**Additional context**
* I had to cleanup automation/* and vars.tfvar files to make `openshift-install-powervs create` work again

**Comment by yussufsh** [comment] 2021-01-05 06:05
If you change anything in the backend then please provide proper variables to the script with new values.

This is not a bug hence closing.

**Closed by yussufsh** 2021-01-05 06:05 UTC
Labels: bug
